{{
   codegen.generate_source(
       schema_name="PREP",
       database_name="ASGMT2",
       table_names=["cust_spin"],
       generate_columns=True,
       include_descriptions=True,
       name="stg_cust",
   )
}}